# Generated by Django 4.1 on 2024-03-09 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Credentials',
            fields=[
                ('status', models.CharField(auto_created=True, default='Active', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('student_id', models.CharField(default='Not Given', max_length=20)),
                ('email', models.CharField(default='Not Given', max_length=255)),
                ('phone', models.CharField(default='Not Given', max_length=50)),
                ('u_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='1234', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_Credentials',
            fields=[
                ('status', models.CharField(auto_created=True, default='Active', max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('emp_id', models.CharField(default='Not Given', max_length=20)),
                ('email', models.CharField(default='Not Given', max_length=255)),
                ('phone', models.CharField(default='Not Given', max_length=50)),
                ('u_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(default='1234', max_length=255)),
                ('exp', models.CharField(default='Advanced', max_length=255)),
                ('budget', models.CharField(default='0', max_length=255)),
                ('meeting_length', models.CharField(default='0000', max_length=255)),
            ],
        ),
    ]
