# Generated by Django 4.1 on 2024-03-09 19:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaConnect', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='Class_Date',
            field=models.CharField(auto_created=True, default=datetime.date(2024, 3, 10), max_length=255),
        ),
        migrations.AlterField(
            model_name='student_credentials',
            name='student_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher_credentials',
            name='teacher_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
