# Generated by Django 4.1 on 2024-03-09 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaConnect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('Students', models.CharField(auto_created=True, default='0', max_length=255)),
                ('Class_Date', models.CharField(auto_created=True, default=datetime.date(2024, 3, 9), max_length=255)),
                ('CLASS_ID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Language', models.CharField(default='-', max_length=255)),
                ('Price', models.CharField(default='0', max_length=255)),
                ('Timing', models.CharField(default='-', max_length=255)),
                ('Teacher', models.CharField(default='-', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('Teacher_ID', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Language', models.CharField(default='-', max_length=255)),
                ('Profeciency', models.CharField(default='Advanced', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='teacher_credentials',
            name='budget',
        ),
        migrations.RemoveField(
            model_name='teacher_credentials',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='teacher_credentials',
            name='exp',
        ),
        migrations.RemoveField(
            model_name='teacher_credentials',
            name='meeting_length',
        ),
        migrations.AddField(
            model_name='student_credentials',
            name='notes',
            field=models.CharField(auto_created=True, default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='teacher_credentials',
            name='teacher_id',
            field=models.AutoField(default='Not Assigned', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student_credentials',
            name='student_id',
            field=models.AutoField(default='Not assigned', primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='student_credentials',
            name='u_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher_credentials',
            name='u_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
