# Generated by Django 4.1 on 2024-03-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaConnect', '0002_classes_teacher_remove_teacher_credentials_budget_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_credentials',
            name='student_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher_credentials',
            name='teacher_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
