# Generated by Django 4.1 on 2024-03-10 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LinguaConnect', '0002_alter_classes_class_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='Profeciency',
            field=models.CharField(default='Elementry', max_length=255),
        ),
    ]
